# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chitatel.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1100, 600))
        MainWindow.setSizeIncrement(QtCore.QSize(1100, 600))
        MainWindow.setBaseSize(QtCore.QSize(1100, 600))
        MainWindow.setStyleSheet("font: 75 8pt \"Courier\";\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.318, x2:1, y2:0.784, stop:0 rgba(101, 78, 163, 1), stop:1 rgba(234, 175, 200, 1));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 290, 1051, 281))
        self.tableWidget.setStyleSheet("background-color: rgb(218, 218, 218);\n"
"border-radius: 5px;")
        self.tableWidget.setDragEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.Dell = QtWidgets.QPushButton(self.centralwidget)
        self.Dell.setGeometry(QtCore.QRect(20, 40, 121, 41))
        self.Dell.setStyleSheet("font: 12pt \"Yu Gothic UI\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 97, 142, 255), stop:0.971591 rgba(191, 178, 221, 255), stop:0.98 rgba(185, 86, 169, 255), stop:1 rgba(185, 86, 169, 0));\n"
"border: (none);")
        self.Dell.setObjectName("Dell")
        self.Add = QtWidgets.QPushButton(self.centralwidget)
        self.Add.setGeometry(QtCore.QRect(20, 90, 121, 41))
        self.Add.setStyleSheet("font: 14pt \"Yu Gothic UI\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 97, 142, 255), stop:0.971591 rgba(191, 178, 221, 255), stop:0.98 rgba(185, 86, 169, 255), stop:1 rgba(185, 86, 169, 0));\n"
"border: (none);")
        self.Add.setObjectName("Add")
        self.Change = QtWidgets.QPushButton(self.centralwidget)
        self.Change.setGeometry(QtCore.QRect(20, 140, 121, 41))
        self.Change.setStyleSheet("font: 14pt \"Yu Gothic UI\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 97, 142, 255), stop:0.971591 rgba(191, 178, 221, 255), stop:0.98 rgba(185, 86, 169, 255), stop:1 rgba(185, 86, 169, 0));\n"
"border: (none);")
        self.Change.setObjectName("Change")
        self.Open = QtWidgets.QPushButton(self.centralwidget)
        self.Open.setGeometry(QtCore.QRect(460, 210, 171, 61))
        self.Open.setStyleSheet("font: 14pt \"Yu Gothic UI\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 97, 142, 255), stop:0.971591 rgba(191, 178, 221, 255), stop:0.98 rgba(185, 86, 169, 255), stop:1 rgba(185, 86, 169, 0));\n"
"border: (none);")
        self.Open.setObjectName("Open")
        self.Back = QtWidgets.QPushButton(self.centralwidget)
        self.Back.setGeometry(QtCore.QRect(960, 0, 141, 51))
        self.Back.setStyleSheet("font: 14pt \"Yu Gothic UI\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 97, 142, 255), stop:0.971591 rgba(191, 178, 221, 255), stop:0.98 rgba(185, 86, 169, 255), stop:1 rgba(185, 86, 169, 0));\n"
"border: (none);")
        self.Back.setObjectName("Back")
        self.DellLine = QtWidgets.QLineEdit(self.centralwidget)
        self.DellLine.setGeometry(QtCore.QRect(150, 40, 101, 41))
        self.DellLine.setStyleSheet("/* Стили для поля ввода */\n"
"QLineEdit {\n"
"    border: 1px solid #2c3e50;\n"
"    border-radius: 1px;\n"
"    padding: 8px;\n"
"    font-size: 13px;\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* Стили для поля ввода при получении фокуса */\n"
"QLineEdit:focus {\n"
"    border-color: #34495e;\n"
"}\n"
"")
        self.DellLine.setText("")
        self.DellLine.setObjectName("DellLine")
        self.AddLine = QtWidgets.QLineEdit(self.centralwidget)
        self.AddLine.setGeometry(QtCore.QRect(260, 90, 101, 41))
        self.AddLine.setStyleSheet("/* Стили для поля ввода */\n"
"QLineEdit {\n"
"    border: 1px solid #2c3e50;\n"
"    border-radius: 1px;\n"
"    padding: 8px;\n"
"    font-size: 13px;\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* Стили для поля ввода при получении фокуса */\n"
"QLineEdit:focus {\n"
"    border-color: #34495e;\n"
"}\n"
"")
        self.AddLine.setObjectName("AddLine")
        self.ChangeLine_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.ChangeLine_1.setGeometry(QtCore.QRect(260, 140, 101, 41))
        self.ChangeLine_1.setStyleSheet("/* Стили для поля ввода */\n"
"QLineEdit {\n"
"    border: 1px solid #2c3e50;\n"
"    border-radius: 1px;\n"
"    padding: 8px;\n"
"    font-size: 13px;\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* Стили для поля ввода при получении фокуса */\n"
"QLineEdit:focus {\n"
"    border-color: #34495e;\n"
"}\n"
"")
        self.ChangeLine_1.setObjectName("ChangeLine_1")
        self.ChangeLine = QtWidgets.QLineEdit(self.centralwidget)
        self.ChangeLine.setGeometry(QtCore.QRect(150, 140, 101, 41))
        self.ChangeLine.setStyleSheet("/* Стили для поля ввода */\n"
"QLineEdit {\n"
"    border: 1px solid #2c3e50;\n"
"    border-radius: 1px;\n"
"    padding: 8px;\n"
"    font-size: 13px;\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* Стили для поля ввода при получении фокуса */\n"
"QLineEdit:focus {\n"
"    border-color: #34495e;\n"
"}\n"
"")
        self.ChangeLine.setObjectName("ChangeLine")
        self.AddLine_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.AddLine_2.setGeometry(QtCore.QRect(370, 90, 101, 41))
        self.AddLine_2.setStyleSheet("/* Стили для поля ввода */\n"
"QLineEdit {\n"
"    border: 1px solid #2c3e50;\n"
"    border-radius: 1px;\n"
"    padding: 8px;\n"
"    font-size: 13px;\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* Стили для поля ввода при получении фокуса */\n"
"QLineEdit:focus {\n"
"    border-color: #34495e;\n"
"}\n"
"")
        self.AddLine_2.setObjectName("AddLine_2")
        self.AddLine_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.AddLine_3.setGeometry(QtCore.QRect(480, 90, 101, 41))
        self.AddLine_3.setStyleSheet("/* Стили для поля ввода */\n"
"QLineEdit {\n"
"    border: 1px solid #2c3e50;\n"
"    border-radius: 1px;\n"
"    padding: 8px;\n"
"    font-size: 13px;\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* Стили для поля ввода при получении фокуса */\n"
"QLineEdit:focus {\n"
"    border-color: #34495e;\n"
"}\n"
"")
        self.AddLine_3.setObjectName("AddLine_3")
        self.AddLine_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.AddLine_4.setGeometry(QtCore.QRect(590, 90, 101, 41))
        self.AddLine_4.setStyleSheet("/* Стили для поля ввода */\n"
"QLineEdit {\n"
"    border: 1px solid #2c3e50;\n"
"    border-radius: 1px;\n"
"    padding: 8px;\n"
"    font-size: 13px;\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* Стили для поля ввода при получении фокуса */\n"
"QLineEdit:focus {\n"
"    border-color: #34495e;\n"
"}\n"
"")
        self.AddLine_4.setObjectName("AddLine_4")
        self.ChangeLine_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.ChangeLine_2.setGeometry(QtCore.QRect(370, 140, 101, 41))
        self.ChangeLine_2.setStyleSheet("/* Стили для поля ввода */\n"
"QLineEdit {\n"
"    border: 1px solid #2c3e50;\n"
"    border-radius: 1px;\n"
"    padding: 8px;\n"
"    font-size: 13px;\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* Стили для поля ввода при получении фокуса */\n"
"QLineEdit:focus {\n"
"    border-color: #34495e;\n"
"}\n"
"")
        self.ChangeLine_2.setObjectName("ChangeLine_2")
        self.ChangeLine_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.ChangeLine_3.setGeometry(QtCore.QRect(480, 140, 101, 41))
        self.ChangeLine_3.setStyleSheet("/* Стили для поля ввода */\n"
"QLineEdit {\n"
"    border: 1px solid #2c3e50;\n"
"    border-radius: 1px;\n"
"    padding: 8px;\n"
"    font-size: 13px;\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* Стили для поля ввода при получении фокуса */\n"
"QLineEdit:focus {\n"
"    border-color: #34495e;\n"
"}\n"
"")
        self.ChangeLine_3.setObjectName("ChangeLine_3")
        self.ChangeLine_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.ChangeLine_4.setGeometry(QtCore.QRect(590, 140, 101, 41))
        self.ChangeLine_4.setStyleSheet("/* Стили для поля ввода */\n"
"QLineEdit {\n"
"    border: 1px solid #2c3e50;\n"
"    border-radius: 1px;\n"
"    padding: 8px;\n"
"    font-size: 13px;\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* Стили для поля ввода при получении фокуса */\n"
"QLineEdit:focus {\n"
"    border-color: #34495e;\n"
"}\n"
"")
        self.ChangeLine_4.setObjectName("ChangeLine_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 10, 16, 16))
        self.label.setStyleSheet("font: 14pt \"Yu Gothic UI\";background: rgba(0,0,0,0.0);;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 90, 101, 41))
        self.label_2.setStyleSheet("font: 15pt \"Yu Gothic UI\";\n"
";\n"
"gridline-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(300, 10, 16, 16))
        self.label_3.setStyleSheet("font: 14pt \"Yu Gothic UI\";background: rgba(0,0,0,0.0);;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(410, 10, 16, 16))
        self.label_4.setStyleSheet("font: 14pt \"Yu Gothic UI\";background: rgba(0,0,0,0.0);;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(520, 10, 16, 16))
        self.label_5.setStyleSheet("font: 14pt \"Yu Gothic UI\";background: rgba(0,0,0,0.0);;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(630, 10, 16, 16))
        self.label_6.setStyleSheet("font: 14pt \"Yu Gothic UI\";background: rgba(0,0,0,0.0);;")
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "drivers"))
        self.Dell.setText(_translate("MainWindow", "Удалить по ID"))
        self.Add.setText(_translate("MainWindow", "Добавить"))
        self.Change.setText(_translate("MainWindow", "Изменить"))
        self.Open.setText(_translate("MainWindow", "Открыть"))
        self.Back.setText(_translate("MainWindow", "Назад"))
        self.label.setText(_translate("MainWindow", "1"))
        self.label_2.setText(_translate("MainWindow", "   Авто ID"))
        self.label_3.setText(_translate("MainWindow", "2"))
        self.label_4.setText(_translate("MainWindow", "3"))
        self.label_5.setText(_translate("MainWindow", "4"))
        self.label_6.setText(_translate("MainWindow", "5"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
