# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1100, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(435, 470))
        MainWindow.setSizeIncrement(QtCore.QSize(435, 470))
        MainWindow.setBaseSize(QtCore.QSize(435, 470))
        MainWindow.setStyleSheet("font: 75 8pt \"Courier\";\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0.318, x2:1, y2:0.784, stop:0 rgba(101, 78, 163, 1), stop:1 rgba(234, 175, 200, 1));")
        MainWindow.setIconSize(QtCore.QSize(38, 24))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AccidentsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.AccidentsBtn.setGeometry(QtCore.QRect(580, 260, 181, 51))
        self.AccidentsBtn.setMaximumSize(QtCore.QSize(33333, 16777215))
        self.AccidentsBtn.setStyleSheet("font: 14pt \"Yu Gothic UI\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 97, 142, 255), stop:0.971591 rgba(191, 178, 221, 255), stop:0.98 rgba(185, 86, 169, 255), stop:1 rgba(185, 86, 169, 0));\n"
"border: (none);\n"
"\n"
"")
        self.AccidentsBtn.setObjectName("AccidentsBtn")
        self.DriversBtn = QtWidgets.QPushButton(self.centralwidget)
        self.DriversBtn.setGeometry(QtCore.QRect(100, 260, 181, 51))
        self.DriversBtn.setMaximumSize(QtCore.QSize(33333, 16777215))
        self.DriversBtn.setStyleSheet("font: 14pt \"Yu Gothic UI\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 97, 142, 255), stop:0.971591 rgba(191, 178, 221, 255), stop:0.98 rgba(185, 86, 169, 255), stop:1 rgba(185, 86, 169, 0));\n"
"border: (none);")
        self.DriversBtn.setObjectName("DriversBtn")
        self.FuelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.FuelBtn.setGeometry(QtCore.QRect(340, 260, 181, 51))
        self.FuelBtn.setMaximumSize(QtCore.QSize(33333, 16777215))
        self.FuelBtn.setStyleSheet("font: 14pt \"Yu Gothic UI\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 97, 142, 255), stop:0.971591 rgba(191, 178, 221, 255), stop:0.98 rgba(185, 86, 169, 255), stop:1 rgba(185, 86, 169, 0));\n"
"border: (none);")
        self.FuelBtn.setObjectName("FuelBtn")
        self.InspectionsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.InspectionsBtn.setGeometry(QtCore.QRect(820, 260, 181, 51))
        self.InspectionsBtn.setMaximumSize(QtCore.QSize(33333, 16777215))
        self.InspectionsBtn.setStyleSheet("font: 14pt \"Yu Gothic UI\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 97, 142, 255), stop:0.971591 rgba(191, 178, 221, 255), stop:0.98 rgba(185, 86, 169, 255), stop:1 rgba(185, 86, 169, 0));\n"
"border: (none);")
        self.InspectionsBtn.setObjectName("InspectionsBtn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(470, 80, 161, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(3333, 16777215))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("font: 75 44pt \"Yu Gothic UI\";\n"
"background: rgba(0,0,0,0.0);")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AccidentsBtn.setText(_translate("MainWindow", "Выдача книг"))
        self.DriversBtn.setText(_translate("MainWindow", "Читатели"))
        self.FuelBtn.setText(_translate("MainWindow", "Издатели"))
        self.InspectionsBtn.setText(_translate("MainWindow", "Книги"))
        self.label.setText(_translate("MainWindow", "Меню"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
